### ISSUE TITLE
Creating Training Polygons - Single or Multi-AOIs

### ISSUE THREAD

**Issue by mmann1123** [jgrss/cultionet#53]
Simple Version:
I guess my question is, can I have multiple 1x1km grid AOIs per poly/grid file?  For example, ` '010101_poly_2022.gpkg'` might have five AOIs with plot bounds.  Or am I allowed only a single AOI per image region? 

More Detail:
I am setting up training data for TZ.  I'm getting confused, from my reading there was miss match between the example data and the docs. But maybe I am wrong.  

In /cultionet/data, the region code doesn't  appear to be related to a {region} defined by the image folder name, and each only seems to contain a single AOI  - **I had assumed this meant that there might be more than one AOI geopackage file per region - which seems impossible given the naming conventions in the doc**

![Screenshot from 2023-03-06 15-32-41](https://user-images.githubusercontent.com/5185364/223224101-61f82bd8-c97d-412c-9778-ecb52ae7ef98.png)

In docs, training dataset seems to refer to single file potentially with multiple AOI polygon features for each {region} - where region is defined by the folder name of the image tile. 
```
project_dir:
  user_train:
    '{region}_grid_{time_series_end_year}.gpkg'
    '{region}_poly_{time_series_end_year}.gpkg'
```

So single file with single 1x1 AOI, single file with multiple AOIs, or multiple files with single AOI each? 

@jgrss

**Comment by jgrss** [comment]
@mmann1123 I would recommend having multiple files with a single AOI each. The initial versions of `cultionet` were setup to support files with multiple AOIs, but that support has sort of faded and it's not well tested.

Sorry if the docs are unclear. The example with training data is meant to show a single grid/polygon pair for one site, but the number of sites is unlimited. I will update the README to show something like:

Train data format:
```
project_dir:
  user_train:
    '{region}_grid_{time_series_end_year}.gpkg'
    '{region}_poly_{time_series_end_year}.gpkg'
```

Example: 

```
project_dir:
  user_train:
    'site1_grid_2021.gpkg'
    'site1_poly_2021.gpkg'
    'site1_grid_2022.gpkg'
    'site1_poly_2022.gpkg'
    'site2_grid_2020.gpkg'
    'site2_poly_2020.gpkg'
    ...
```

**Comment by mmann1123** [comment]
@jgrss  Ok so the region doesn't need to be in the poly name. Got it. Thanks!

**Comment by jgrss** [comment]
Sorry, it does actually. The `{region}` in the template needs to be replaced with a region name, which can be a unique string or 6-character integer (e.g., 000001). In the second example, the regions are 'site1' and 'site2'.

```yaml
project_dir:
  user_train:
    'site1_grid_2021.gpkg'
    'site1_poly_2021.gpkg'
    'site1_grid_2022.gpkg'
    'site1_poly_2022.gpkg'
    'site2_grid_2020.gpkg'
    'site2_poly_2020.gpkg'
    ...
```

See an [updated version of the README](https://github.com/jgrss/cultionet/tree/jgrss/topo_v2_time_rnn_nobal_batch_act_dgm_test).

**Comment by jgrss** [comment]
Oh, maybe you meant that '{region}' doesn't need to be in the filenames? Anything within and including `{}` is meant to illustrate the format and should be replaced with your names and years. E.g., `'{region}_grid_{time_series_end_year}.gpkg'` should be `'A_grid_2022.gpkg'` for region A, year 2022.

**Comment by mmann1123** [comment]
Ok I think I am seeing the issue now. So the {region} has to match the image folder and the name of the grid or poly. 


```   
time_series_vars:
      image1:
          evi2:
             2021001.tif
             2021014.tif
      image2:
          evi2:
              2021001.tif
              2021014.tif
project_dir:
   user_train:
       'image1_grid_2022.gpkg'
       'image1_poly_2022.gpkg'
       'image1_grid_2022.gpkg'
       'image2_poly_2022.gpkg'
```

What threw me off is I thought you said that I could only have one box of training data in a given '_poly_.gpkg'.  So I was creating multiple .gpkg for the same image/year. @jgrss
