### ISSUE TITLE
AssertionError: The maximum crop class value must be given

### ISSUE THREAD

**Issue by mmann1123** [jgrss/cultionet#61]
@jgrss  Thanks for your help with this. I have tried tons of variants of training data to resolve this issue

 I have my training data in the correct locations 
![Screenshot from 2023-03-09 10-24-05](https://user-images.githubusercontent.com/5185364/224070927-98cb6b28-a08a-495a-b3b7-5b4b88e66f1b.png)

I have tried every variant of handling the "class" field I could think of ( I have quite a few polygons with 0 fields). I have created empty _poly_ and non-empty _poly_ with class=0.  So I think I can conclude that is not the problem. Maybe there's something simple I am missing? 

```
cultionet create --project-path /home/ubuntu/training_data --grid-size 100 100 --config-file ./config.yml
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch/bin/cultionet", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/cultionet/scripts/cultionet.py", line 1275, in main
    create_datasets(args)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/cultionet/scripts/cultionet.py", line 712, in create_datasets
    assert isinstance(args.max_crop_class, int), \
AssertionError: The maximum crop class value must be given.
```
Also tried:
```
cultionet create --project-path /home/ubuntu/training_data --grid-size 100 100 --config-file ./config.yml --max_crop_class 1
usage: cultionet [-h] {create,create-predict,skfoldcv,train,maskrcnn,predict,version} ...
cultionet: error: unrecognized arguments: --max_crop_class 1
```

**Comment by jgrss** [comment]
Try `--max-crop-class 1`. The CLI arguments are character sensitive. [Here](https://github.com/jgrss/cultionet/blob/jgrss/topo_v2_time_rnn_nobal_batch_act_dgm_test/scripts/01a_create_data.sh) is a script for reference.

**Comment by mmann1123** [comment]
hah... yeah that was stupid. I typed `--max_crop_class` sorry..

**Comment by mmann1123** [comment]
@jgrss it is now asking for the region id file

```
cultionet create --project-path /home/ubuntu/training_data --grid-size 100 100 --config-file /home/ubuntu/cultionet/scripts/config.yml  --max-crop-class 1 --feature-pattern {region}/{image_vi} --image-date-format %Y%j
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch/bin/cultionet", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/cultionet/scripts/cultionet.py", line 1394, in main
    create_datasets(args)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/cultionet/scripts/cultionet.py", line 709, in create_datasets
    region_as_file = config["region_id_file"] is not None
KeyError: 'region_id_file'
```

I noticed that you added something to one of the config file examples. when I add this to my config 
```
# The region file path
region_id_file: !!null
```
I get the following:
```
cultionet create --project-path /home/ubuntu/training_data --grid-size 100 100 --config-file /home/ubuntu/cultionet/scripts/config.yml  --max-crop-class 1 --image-date-format %Y%j
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch/bin/cultionet", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/cultionet/scripts/cultionet.py", line 1394, in main
    create_datasets(args)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/cultionet/scripts/cultionet.py", line 734, in create_datasets
    range(config["regions"][0], config["regions"][1] + 1)
TypeError: can only concatenate str (not "int") to str
```
I can't find any reference to what this file should be, I tried pointing it to the imagery path but that wasn't it.  Any thoughts?  Maybe you could share your config?

**Comment by jgrss** [comment]
Ahh, you can either use `regions` or `region_id_file` in the `config.yml` file. E.g., you could do either
```yaml
regions: [1, 10]
region_id_file: !!null
```
to process regions 1 through 10, or
```yaml
regions: [1, 3, 5]
region_id_file: !!null
```
to process regions 1, 3, and 5.

If, however, your names are strings, you might want to use `region_id_file` like
```yaml
regions: !!null
region_id_file: /path/to/an/id/file.csv
```
where `/path/to/an/id/file.csv` might look like
```text
,id
0,region_a
1,region_b
...
n,region_n
```
In the file, the column id is 'id', the first column is a `GeoDataFrame` index and the second column is the region id.

Note that the creation of a train data .pt file will be attempted for every region/year combination. So in `config.yml` if you have
```yaml
years:
  - 2020
  - 2021
  - 2022
```
The creation step will try to create `region_a + 2020`, `region_a + 2021`, and `region_a + 2022`. If training files do not exist for some years, it will just skip it.

**Comment by mmann1123** [comment]
Gotcha in the config.yml in the scripts folder it shows:
```
# The regions to process (start, end)
regions:
  - 161
  - 171
```
That is not working

**Comment by mmann1123** [comment]
Looks like the region id file might have an issue. I added the correct path (certain of that) in the config:

`region_id_file: /home/ubuntu/ym_field_boundaries/regions.csv`

Where the contents of  `regions.csv` are:
```
,id
0,0000000000-0000016384
1,0000016384-0000000000
2,0000016384-0000016384
```

I am getting:

`File not exist: : 6it [00:00, 2784.45it/s]`              

Renaming my image folders 1,2,3 resolved the issue and just using 
```
regions:
   - 1
   - 2
   - 3
```    
Although now I am finally hitting the wall of an incorrect install... unrelated to this issue.

**Comment by jgrss** [comment]
Regarding `File not exist: : 6it [00:00, 2784.45it/s]`, I think there is a small progress bar bug in cultionet. I don't think there was anything wrong with your id format (e.g., 000000000-0000016384). The progress bar is broken and prints out different logs. If it says 'File not exist' then that could be fine. Remember, for each region it will check if there is a region/year combination for every year.

You can check `<your project path>/data/train/processed` to see if outputs are being created.

**Comment by mmann1123** [comment]
Data `<your project path>/data/train/processed` is empty.  Maybe this is a projections issue? My images are in 4326 and polys in UTM.

**Comment by mmann1123** [comment]
Just reprojected the polys and grids to match the crs of the images. Same issue. Empty `/train/processed`.

**Comment by jgrss** [comment]
@mmann1123 how do you have your image time series setup? I think you have one image to cover your study area, correct? What you should have is something like:
```yaml
time_series_vars/
    001458/
        evi/
    004604/
        evi/

user_train/
    001458_grid_2022.gpkg
    001458_poly_2022.gpkg
    004604_grid_2022.gpkg
    004604_poly_2022.gpkg
```
but I think you have:
```yaml
time_series_vars/
    evi/
```

You could have the same, large image for each `time_series_vars/` sub-region, but that would be wasted disk space. Therefore, I would clip your time series variables to each region.

Also, if you want to work on a branch, #64 has a fix for the data progress bar.

**Comment by mmann1123** [comment]
@jgrss I tried to recreate exactly what you did 
 
`/home/ubuntu/training_data` 
![Screenshot from 2023-03-21 16-13-16](https://user-images.githubusercontent.com/5185364/226729907-cb6fca74-6023-4c30-b5ab-f240bb5b29c4.png)

`/home/ubuntu/cultionet/scripts/config.yml`
```
image_vis:
  - evi

# The regions to process (start, end)
regions:   
  - 000001
  - 000002
  - 000003

# The region file path
region_id_file: #/home/ubuntu/ym_field_boundaries/regions.csv


years:
  - 2022
  - 2023

lc_path: !!null
```

and `cultionet create --project-path /home/ubuntu/training_data --grid-size 100 100 --config-file /home/ubuntu/cultionet/scripts/config.yml  --max-crop-class 1 --image-date-format %Y%j`

Still getting `File not exist: : 4it [00:00, 3501.09it/s]` and nothing in `project/data/train/processed/`

I don't know how to debug things from the command line. Is there a python command I can run to execute the same operation??

**Comment by jgrss** [comment]
Ahh, I have the vector files extension hardcoded as .gpkg. I'll put in an issue to allow other formats, such as .geojson.

**Comment by mmann1123** [comment]
Ha well on to the next error, and nothing created in the `data/train/processed` folder unfortunately. 
`No directory: : 8it [00:00, 51.58it/s] `

**Comment by mmann1123** [comment]
@jgrss  Well, now I'm 90% sure I have the data set up correctly, but still getting the `No directory` or `File not exist` with nothing generated in `data/train/processed`

I have an example dataset and config here.  Hoping you could take a look:

[link to data](https://www.dropbox.com/scl/fo/ctrpgocf7oe1utfle591y/h?dl=0&rlkey=tv1r9ese38coidakzezl2n02v)

I promise I will go through your docs and make everything clear once I get this working!

**Comment by jgrss** [comment]
> @jgrss  Well, now I'm 90% sure I have the data set up correctly, but still getting the `No directory` or `File not exist` with nothing generated in `data/train/processed`
> 
> I have an example dataset and config here.  Hoping you could take a look:
> 
> [link to data](https://www.dropbox.com/scl/fo/ctrpgocf7oe1utfle591y/h?dl=0&rlkey=tv1r9ese38coidakzezl2n02v)
> 
> I promise I will go through your docs and make everything clear once I get this working!
> 
> 
> 
> I did manage to figure out a way to get a error traceback, created my own test:
> 
> ```
> 
> test_augmentation.py::test_feature_stack_to_tsaug PASSED                                                                                                 [  5%]
> test_augmentation.py::test_augmenter_loading PASSED                                                                                                      [ 11%]
> test_create_dataset.py::test_predict_dataset PASSED                                                                                                      [ 16%]
> test_create_dataset_mike.py::test_predict_dataset FAILED                                                                                                 [ 22%]
> test_dataset.py::test_load PASSED                                                                                                                        [ 27%]
> test_dataset.py::test_ds_type PASSED                                                                                                                     [ 33%]
> test_dataset.py::test_ds_len PASSED                                                                                                                      [ 38%]
> test_dataset.py::test_x_type PASSED                                                                                                                      [ 44%]
> test_dataset.py::test_x_shape PASSED                                                                                                                     [ 50%]
> test_dataset.py::test_y_shape PASSED                                                                                                                     [ 55%]
> test_dataset.py::test_dims_attr PASSED                                                                                                                   [ 61%]
> test_loss.py::test_tanimoto_loss PASSED                                                                                                                  [ 66%]
> test_norm.py::test_cumnorm_serial PASSED                                                                                                                 [ 72%]
> test_norm.py::test_cumnorm_concurrent PASSED                                                                                                             [ 77%]
> test_norm.py::test_transform_data PASSED                                                                                                                 [ 83%]
> test_reshape.py::test_graph_to_conv PASSED                                                                                                               [ 88%]
> test_reshape.py::test_conv_to_graph PASSED                                                                                                               [ 94%]
> test_reshape.py::test_conv_to_time PASSED                                                                                                                [100%]
> 
> =========================================================================== FAILURES ===========================================================================
> _____________________________________________________________________ test_predict_dataset _____________________________________________________________________
> 
>     def test_predict_dataset():
>         ppaths = setup_paths(".", append_ts=True)
>         image_list = get_image_list()
>     
> >       create_predict_dataset(
>             image_list=image_list,
>             region=REGION,
>             year=END_YEAR,
>             process_path=ppaths.get_process_path("predict"),
>             gain=1e-4,
>             offset=0.0,
>             ref_res=10.0,
>             resampling="nearest",
>             window_size=50,
>             padding=5,
>             num_workers=2,
>             chunksize=100,
>         )
> 
> test_create_dataset_mike.py:36: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> /opt/conda/envs/pytorch/lib/python3.9/site-packages/cultionet/data/create.py:595: in create_predict_dataset
>     with gw.open(
> /opt/conda/envs/pytorch/lib/python3.9/site-packages/geowombat/core/api.py:506: in __init__
>     self.data = gw_concat(
> /opt/conda/envs/pytorch/lib/python3.9/site-packages/geowombat/backends/xarray_.py:603: in concat
>     src_ = warp_open(
> /opt/conda/envs/pytorch/lib/python3.9/site-packages/geowombat/backends/xarray_.py:296: in warp_open
>     warp(filename, resampling=resampling, **ref_kwargs),
> /opt/conda/envs/pytorch/lib/python3.9/site-packages/geowombat/backends/rasterio_.py:976: in warp
>     output = WarpedVRT(src, **vrt_options)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> >   ???
> E   RuntimeError: Parameterization error
> 
> rasterio/_warp.pyx:1087: RuntimeError
> ```
> Thinking this might be helpful.  So it looks like its just not finding the files to open? 

I haven't looked at the new data link yet. Did you convert your GeoJSONs to GPKGs?

**Comment by mmann1123** [comment]
I kept playing and found that it was generating the image list properly, so that's not it.

**Comment by mmann1123** [comment]
Yes they are all geopackages and I think in the correct format.... @jgrss

**Comment by jgrss** [comment]
@mmann1123 There are a few things going on.

1. I `symlinked` your data to the same path as the project directory.

```commandline
ln -s training_data/time_series_vars time_series_vars
ln -s training_data/user_train user_train
```

2. Two arguments are missing from the command line (`--feature-pattern` and `--start-date` and `--end-date`. The default path layout does not match what you have setup, so the `--feature-pattern` tells `cultionet` where to look for the time series data. The default start and end date assumes a Northern hemisphere season. There is a check for Southern hemisphere images that catches if you leave the start/end dates as 1 January. I do not know the typical agricultural season(s) in your study area so I just used a generic 1 July cycle. I edited the bash file to look like:
```commandline
# source {path}/.pyenv/versions/venv.cnet/bin/activate

cultionet create \
        --project-path . \
        --config-file config.yml \
        --crop-column class \
        --grid-size 100 100 \
        --max-crop-class 1 \
        --image-date-format %Y%j \
        --feature-pattern {region}/{image_vi} \
        --start-date 07-01 \
        --end-date 07-01
```

3. Your training years do not match the time series years. The year should be the end year of the time series. E.g., I had to rename `000002_grid_2022.gpkg` and `000002_poly_2022.gpkg` to `000002_grid_2023.gpkg` and `000002_poly_2023.gpkg`, respectively. 

5. There is a missing column in your grid files. The grid files should have a 'region' or 'grid' column that specifies the unique grid id. This is probably a failure by me to explain this in the README. You can use [this branch](https://github.com/jgrss/cultionet/tree/jgrss/issue_63) to have the column added automatically from the file name.

With those changes the .pt files were generated for grid 2.

**Comment by jgrss** [comment]
Ahh, good one. Thanks for pointing that out.

**Comment by mmann1123** [comment]
@jgrss  Ok some progress forward. 

It looks like is choking when it runs into an image shard with all zeros in it (not sure how I generated it, but its failing on that).

But happy to say its generating `.pt` files. I try deleting the offending image. 

```
ultionet create \
        --res 0.0000898315284119(pytorch_backup_april_11) ubuntu@ip-10-0-2-97:~/training_data$ 
5214829 \
        --project-path . \
        --con(pytorch_backup_april_11) ubuntu@ip-10-0-2-97:~/training_data$ cultionet create \
>         --res 0.00008983152841195214829 \
>         --project-path . \
>         --config-file config.yml \
>         --crop-column class \
>         --grid-size 99 99 \
>         --max-crop-class 1 \
>         --image-date-format %Y%j \
>         --feature-pattern {region}/{image_vi} \
>         --start-date 05-01 \
>         --end-date 05-01

000004_2022 stored.:  12%|████████████████▉                                                                                                                      | 6/48 [00:02<00:16,  2.57it/s]
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch_backup_april_11/bin/cultionet", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/pytorch_backup_april_11/lib/python3.9/site-packages/cultionet/scripts/cultionet.py", line 1401, in main
    create_datasets(args)
  File "/opt/conda/envs/pytorch_backup_april_11/lib/python3.9/site-packages/cultionet/scripts/cultionet.py", line 873, in create_datasets
    pbar = create_dataset(
  File "/opt/conda/envs/pytorch_backup_april_11/lib/python3.9/site-packages/cultionet/data/create.py", line 907, in create_dataset
    aug_data = aug_method(ldata, aug_args=augmenters.aug_args)
  File "/opt/conda/envs/pytorch_backup_april_11/lib/python3.9/site-packages/cultionet/augment/augmenters.py", line 49, in __call__
    cdata = self.forward(cdata, ldata, aug_args)
  File "/opt/conda/envs/pytorch_backup_april_11/lib/python3.9/site-packages/cultionet/augment/augmenters.py", line 148, in forward
    x = augment_time(
  File "/opt/conda/envs/pytorch_backup_april_11/lib/python3.9/site-packages/cultionet/augment/augmenter_utils.py", line 111, in augment_time
    np.random.choice(
  File "mtrand.pyx", line 934, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken
```

**Comment by mmann1123** [comment]
@jgrss  It generated `pt` files from `000002` to `000005`.  So I deleted region `000006` because it only had zero in the image. 
Tried rerunning but getting same error as above (`00007`) looks fine, so not sure what's happening.

**Comment by jgrss** [comment]
That's related to the temporal resolution. The coarsest that I have tried recently is monthly. Are you using seasonal data?

**Comment by jgrss** [comment]
Okay, I should have a protection in there for the peaks transformation. For now, you should just exclude that augmentation.
