### ISSUE TITLE
[documentation] Information about region numbering

### ISSUE THREAD

**Issue by MatthewPierson90** [jgrss/cultionet#7]
It would be useful if it were mentioned in the documentation that regions have to be 6 digits with 0's as place holders.

**Comment by jgrss** [comment]
Good point. I show that below, but didn't make it clear that it is mandatory. I'll fix that.

> The years in the directories must align with the training data files. More specifically, the training data year (year in the polygon/grid pairs) should correspond to the time series end year.
For example, a file named 000001_poly_2020.gpkg should be trained on 2019-2020 imagery, while 000001_poly_2022.gpkg would match a 2021-2022 time series.
