### ISSUE TITLE
[bug] EdgeDataset processed path

### ISSUE THREAD

**Issue by MatthewPierson90** [jgrss/cultionet#8]
I don't think that this affects functionality, but I did come across it. 

When calling EdgeDataset, if I call 
ds = EdgeDataset(root = data_directory_path)
where data_directory has the structure
data_directory:
  processed:
    data1
    data2
    ...

Then the EdgeDataset.processed_paths have an additional 'data_directory_path/processed' at the the beginning of the path. 

IE it results in
'data_directory_path/processed/data_directory_path/processed/data1'
instead of 
'data_directory_path/processed/data1'

**Comment by jgrss** [comment]
That is the expected layout, but I will try to make it clearer in the README. Essentially, you just want to pass the base/parent directory.

**Comment by MatthewPierson90** [comment]
That makes sense. I was exploring using a slightly different directory structure (specifically if I have the training data in a different location than data/processed).

**Comment by jgrss** [comment]
> That makes sense. I was exploring using a slightly different directory structure (specifically if I have the training data in a different location than data/processed).

Ah, I see. I think I will close this since the directory layout is tied to PyTorch.
